"""empty message

Revision ID: 2b2ebf58efd0
Revises: 
Create Date: 2020-05-15 23:36:40.580374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2ebf58efd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('ib_conn_id', sa.Integer(), nullable=False),
    sa.Column('granular', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equity_historical_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('equity_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('barSize', sa.Enum('SEC_1', 'SEC_5', 'SEC_10', 'SEC_15', 'SEC_30', 'MIN_1', 'MIN_2', 'MIN_3', 'MIN_5', 'MIN_10', 'MIN_15', 'MIN_20', 'MIN_30', 'HOUR_1', 'HOUR_2', 'HOUR_3', 'HOUR_4', 'HOUR_8', 'DAY_1', 'WEEK_1', 'MONTH_1', name='barsizes'), nullable=False),
    sa.Column('dataType', sa.Enum('TRADES', 'MIDPOINT', 'BID', 'ASK', 'BID_ASK', 'HISTORICAL_VOLATILITY', 'OPTION_IMPLIED_VOLATILITY', name='historicaldatatype'), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('barCount', sa.Float(), nullable=False),
    sa.Column('average', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['equity_id'], ['equity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equity_historical_data')
    op.drop_table('equity')
    # ### end Alembic commands ###
