"""empty message

Revision ID: e964ad7fa35a
Revises: 2b2ebf58efd0
Create Date: 2020-05-16 18:24:13.044906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e964ad7fa35a'
down_revision = '2b2ebf58efd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equity', sa.Column('ib_con_id', sa.Integer(), nullable=False))
    op.add_column('equity', sa.Column('name', sa.String(length=256), nullable=False))
    op.add_column('equity', sa.Column('should_update', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'equity', ['ticker'])
    op.drop_column('equity', 'ib_conn_id')
    op.add_column('equity_historical_data', sa.Column('bar_count', sa.Float(), nullable=False))
    op.add_column('equity_historical_data', sa.Column('bar_size', sa.Enum('SEC_1', 'SEC_5', 'SEC_10', 'SEC_15', 'SEC_30', 'MIN_1', 'MIN_2', 'MIN_3', 'MIN_5', 'MIN_10', 'MIN_15', 'MIN_20', 'MIN_30', 'HOUR_1', 'HOUR_2', 'HOUR_3', 'HOUR_4', 'HOUR_8', 'DAY_1', 'WEEK_1', 'MONTH_1', name='barsizes'), nullable=False))
    op.add_column('equity_historical_data', sa.Column('data_type', sa.Enum('TRADES', 'MIDPOINT', 'BID', 'ASK', 'BID_ASK', 'HISTORICAL_VOLATILITY', 'OPTION_IMPLIED_VOLATILITY', name='historicaldatatype'), nullable=False))
    op.drop_column('equity_historical_data', 'dataType')
    op.drop_column('equity_historical_data', 'barCount')
    op.drop_column('equity_historical_data', 'barSize')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equity_historical_data', sa.Column('barSize', mysql.ENUM('SEC_1', 'SEC_5', 'SEC_10', 'SEC_15', 'SEC_30', 'MIN_1', 'MIN_2', 'MIN_3', 'MIN_5', 'MIN_10', 'MIN_15', 'MIN_20', 'MIN_30', 'HOUR_1', 'HOUR_2', 'HOUR_3', 'HOUR_4', 'HOUR_8', 'DAY_1', 'WEEK_1', 'MONTH_1', collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('equity_historical_data', sa.Column('barCount', mysql.FLOAT(), nullable=False))
    op.add_column('equity_historical_data', sa.Column('dataType', mysql.ENUM('TRADES', 'MIDPOINT', 'BID', 'ASK', 'BID_ASK', 'HISTORICAL_VOLATILITY', 'OPTION_IMPLIED_VOLATILITY', collation='utf8mb4_unicode_ci'), nullable=False))
    op.drop_column('equity_historical_data', 'data_type')
    op.drop_column('equity_historical_data', 'bar_size')
    op.drop_column('equity_historical_data', 'bar_count')
    op.add_column('equity', sa.Column('ib_conn_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'equity', type_='unique')
    op.drop_column('equity', 'should_update')
    op.drop_column('equity', 'name')
    op.drop_column('equity', 'ib_con_id')
    # ### end Alembic commands ###
